### ISSUE TITLE
README says sy default to sx 

### ISSUE THREAD

**Issue by dmnsgn** [vorg/primitive-plane#4]
Actually default to 1: https://github.com/vorg/primitive-plane/blob/30abcbafbe76ce161df5f4024b07aaeab799c10f/index.js#L9

**Comment by vorg** [comment]
I says sx because it should. Just like primitive-cube. Bug is in code. Should be sy || sx || 1

**Comment by dmnsgn** [comment]
PR updated using sx and nx as default to their y counterparts (as in `primitive-cube`):

https://github.com/vorg/primitive-plane/blob/7b4317e3188878b1370274e175c4219671615b91/index.js#L8-L11
